-- Упрощенная схема для тестов
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE items (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(1024) NOT NULL,
                       is_available BOOLEAN NOT NULL,
                       owner_id BIGINT NOT NULL,
                       request_id BIGINT,
                       FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          start_date TIMESTAMP NOT NULL,
                          end_date TIMESTAMP NOT NULL,
                          item_id BIGINT NOT NULL,
                          booker_id BIGINT NOT NULL,
                          status VARCHAR(20) NOT NULL,
                          FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
                          FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          text VARCHAR(1024) NOT NULL,
                          item_id BIGINT NOT NULL,
                          author_id BIGINT NOT NULL,
                          created TIMESTAMP NOT NULL,
                          FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
                          FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE requests (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description VARCHAR(512) NOT NULL,
                          requestor_id BIGINT NOT NULL,
                          created TIMESTAMP,
                          FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
);
