-- Универсальная схема для H2 и PostgreSQL
-- Для H2 убраны IF NOT EXISTS, так как они не поддерживаются в DDL

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(512) NOT NULL,
                       CONSTRAINT pk_user PRIMARY KEY (id),
                       CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE requests (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          description VARCHAR(512) NOT NULL,
                          requestor_id BIGINT NOT NULL,
                          created TIMESTAMP,
                          CONSTRAINT pk_request PRIMARY KEY (id),
                          CONSTRAINT fk_requests_requestor FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE items (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(1024) NOT NULL,
                       is_available BOOLEAN NOT NULL,
                       owner_id BIGINT NOT NULL,
                       request_id BIGINT,
                       CONSTRAINT pk_item PRIMARY KEY (id),
                       CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
                       CONSTRAINT fk_items_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE SET NULL
);

CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          start_date TIMESTAMP NOT NULL,
                          end_date TIMESTAMP NOT NULL,
                          item_id BIGINT NOT NULL,
                          booker_id BIGINT NOT NULL,
                          status VARCHAR(20) NOT NULL,
                          CONSTRAINT pk_booking PRIMARY KEY (id),
                          CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
                          CONSTRAINT fk_bookings_booker FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          text VARCHAR(1024) NOT NULL,
                          item_id BIGINT NOT NULL,
                          author_id BIGINT NOT NULL,
                          created TIMESTAMP NOT NULL,
                          CONSTRAINT pk_comment PRIMARY KEY (id),
                          CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
                          CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);
